// Run through run_detection_review_smoke.py against its synthetic, temporary drawing.
const assert = require("node:assert/strict");
const { chromium } = require("playwright");
(async () => {
  const browser = await chromium.launch({executablePath:process.env.CHROME_PATH, headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  const errors = [];
  page.on("pageerror", error => errors.push(String(error)));
  page.on("dialog", dialog => dialog.accept());
  try {
    await page.goto(process.argv[2]);
    await page.locator("#items button").first().waitFor();
    await page.locator("#languageSwitch").selectOption("zh-CN");
    assert.equal(await page.locator("h1").textContent(), "图例与符号审核");
    assert.equal(await page.locator("#focus").textContent(), "定位选中项");
    await page.locator("#legendType").selectOption("library");
    assert.equal(await page.locator("#items button").count(),1);
    await page.locator("#items button").click();
    assert(await page.locator("#focus").isDisabled());
    assert((await page.locator("#inspector").textContent()).includes("并非从本 PDF 中提取"));
    await page.locator("#legendType").selectOption("text");
    assert.equal(await page.locator("#items button").count(),1);
    await page.locator("#legendType").selectOption("drawing");
    await page.locator("#items button").click();
    assert.equal(await page.locator("#page").inputValue(), "0");
    assert.equal(await page.locator("#drawing rect.active").count(),1);
    await page.locator("#legendType").selectOption("all");
    await page.locator("#bulk").click();
    await page.waitForFunction(() => document.querySelector("#summary").textContent.includes("3/3"));
    await page.locator("#symbolTab").click();
    await page.locator("#page").selectOption("1");
    await page.locator('#items [data-item-id="proposal-0"]').click();
    assert.equal(await page.locator("#editKind").inputValue(), "raster_symbol", "A broad observation must not silently default to equipment");
    assert((await page.locator("#inspector").textContent()).includes("Flow arrow; retain as direction evidence"));
    await page.locator("#save").click();
    await page.locator("#error").waitFor({state:"visible"});
    assert((await page.locator("#error").textContent()).includes("Classify the raster symbol"));
    await page.locator("#pending").click();
    await page.waitForFunction(() => !busy && document.querySelector("#error").classList.contains("hidden"));
    assert.equal(await page.locator("#editKind").inputValue(), "raster_symbol");
    await page.locator("#reject").click();
    await page.waitForFunction(() => !document.querySelector('#items [data-item-id="proposal-0"]'));
    await page.locator('[data-item-id="d2"]').first().click();
    const selected=page.locator("#drawing rect.active");
    assert.equal(await selected.getAttribute("stroke"),"#c026d3");
    const viewport=await page.locator("#viewport").boundingBox();
    const bounds=await selected.boundingBox();
    assert(bounds.width >= 100, "Tiny symbols must be zoomed into a readable size");
    assert(Math.abs(bounds.x+bounds.width/2-(viewport.x+viewport.width/2))<5,"Selection centered horizontally");
    assert(Math.abs(bounds.y+bounds.height/2-(viewport.y+viewport.height/2))<5,"Selection centered vertically");
    assert.equal(await page.locator("#drawing .selection-halo").count(),1);
    assert.equal(await page.locator("#drawing .focused-source").count(),1);
    assert(await page.locator("#drawing .muted").count()>0);
    assert.equal(await page.locator("#inspector svg.source-detail rect").count(),1);
    assert((await page.locator("#selectionLabel").textContent()).includes("PT-002"));
    await page.locator("#editLabel").fill("UNSAVED-TAG");
    await page.locator("#languageSwitch").selectOption("en");
    assert.equal(await page.locator("#editLabel").inputValue(),"UNSAVED-TAG");
    assert.equal(await page.locator("#drawing rect.active").getAttribute("data-item-id"),"d2");
    await page.locator("#languageSwitch").selectOption("zh-CN");
    assert.equal(await page.locator("#editLabel").inputValue(),"UNSAVED-TAG");
    await page.locator("#fit").click();
    assert.equal(await page.locator("#zoomLabel").textContent(),"100%");
    await page.locator("#focus").click();
    assert.notEqual(await page.locator("#zoomLabel").textContent(),"100%");
    await page.locator("#autoFocus").uncheck();
    await page.locator("#fit").click();
    await page.locator('#items [data-item-id="d1"]').click();
    assert.equal(await page.locator("#zoomLabel").textContent(),"100%");
    await page.locator("#autoFocus").check();
    await page.locator('#items [data-item-id="d2"]').click();
    await page.screenshot({path:process.argv[3],fullPage:true});
    await page.reload();
    await page.waitForFunction(() => document.querySelector("#page").options.length === 2);
    assert.equal(await page.locator("#languageSwitch").inputValue(),"zh-CN");
    await page.locator("#symbolTab").click();
    await page.locator("#page").selectOption("1");
    await page.locator('#items [data-item-id="d2"]').click();
    assert.equal(await page.locator("#editLabel").inputValue(),"PT-002", "Language switching must not save edits");
    await page.locator("#editLabel").fill("PT-REVIEWED");
    await page.locator("#save").click();
    await page.waitForFunction(() => document.querySelector("#summary").textContent.includes("已确认符号 1"));
    await page.locator("#bulk").click();
    await page.waitForFunction(() => document.querySelector("#summary").textContent.includes("已确认符号 2"));
    await page.locator("#rejectCandidates").click();
    await page.waitForFunction(() => document.querySelector("#summary").textContent.includes("待审核符号 0"));
    await page.locator("#fit").click();
    await page.locator("#add").click();
    const svg=await page.locator("#drawing").boundingBox();
    await page.mouse.move(svg.x+svg.width*.2,svg.y+svg.height*.3);
    await page.mouse.down();await page.mouse.move(svg.x+svg.width*.25,svg.y+svg.height*.4);await page.mouse.up();
    await page.locator("#editLabel").fill("NEW-SYMBOL");
    await page.locator("#languageSwitch").selectOption("en");
    assert.equal(await page.locator("#editLabel").inputValue(),"NEW-SYMBOL", "An unsaved manual symbol survives the language switch");
    await page.locator("#equipment_class").fill("pump");
    await page.locator("#save").click();
    await page.waitForFunction(() => document.querySelector("#summary").textContent.includes("3 symbols confirmed"));
    await page.locator("#coverage").check();
    await page.waitForFunction(() => !document.querySelector("#build").disabled);
    await page.locator("#build").click();
    await page.locator("#buildReviewedButton").waitFor({state:"visible"});
    await page.locator("#buildReviewedButton").click();
    await page.waitForFunction(() => document.querySelector("#jobState").textContent === "Finished");
    assert(!(await page.locator("#jobError").isVisible()));
    assert.deepEqual(errors,[]);
    console.log("Passed: broad observations remain unclassified, confirmation is gated, arrow exclusion preserves evidence, Chinese/English, persistence, unsaved edits, legend source types, cross-page selection, focus geometry, highlight, source detail, manual drawing, review saves and reviewed graph build.");
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
